### PR TITLE
Webhook/dipty

### PR DESCRIPTION
**Pull request by diptyojha**

### CODE REVIEW

**Comment by diptyojha** [comment]
[Offers Service: Send Offer details to Partner through Webhook](https://trello.com/c/DzimI3aW/123-offers-service-send-offer-details-to-partner-through-webhook)

**Comment by diptyojha** [comment]
[Offers Service: Send Offer details to Partner through Webhook](https://trello.com/c/DzimI3aW/123-offers-service-send-offer-details-to-partner-through-webhook)

**Comment by diptyojha** [comment]
[Offers Service: Send Offer details to Partner through Webhook](https://trello.com/c/DzimI3aW/123-offers-service-send-offer-details-to-partner-through-webhook)

**Review by piggy1-mvn — APPROVED** [review]

**Comment by piggy1-mvn** [comment]
[Notification: Fail to send webhook to partner](https://trello.com/c/KVn1esze/137-notification-fail-to-send-webhook-to-partner)

**Pull request merged**
